version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internal
      - external

  php-fpm:
    build:
      ./php-fpm
    container_name: php-fpm
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - internal
      - external
    volumes:
      - ../:/var/www/html
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini

  webserver:
    image: nginx:1.17.4-alpine
    container_name: webserver
    depends_on:
      - php-fpm
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ../:/var/www/html
      - ./nginx/nginx-conf:/etc/nginx/conf.d
    networks:
      - external

networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
  db-data:
