<?php

/**
 * @file
 * Contains wristcheck_basic.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Markup;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_help().
 */
function wristcheck_basic_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the wristcheck_basic module.
    case 'help.page.wristcheck_basic':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('WristCheck Basic functions &amp; forms &amp; configurations &amp; pages.') . '</p>';
      return $output;

    default:
  }
}

/**
 * @param $key
 * @param $message
 * @param $params
 *  hook_mail
 */
function wristcheck_basic_mail($key, &$message, $params) {
  if ($key == 'smtp-test') {
    $message['subject'] = $params['subject'];
    $message['body'][] = $params['body'];
  }
}

/**
 * @param $form
 * @param $form_state
 * @param $form_id
 * faq authsystem
 */
function wristcheck_basic_form_alter(&$form, &$form_state, $form_id){
  if($form_id == "webform_submission_faq_authsystem_add_form"){
    $form['actions']['submit']['#type'] = 'button';
  }
}
//function wristcheck_basic_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
////  exit('hello');
//  var_dump($build);
//  var_dump($block);
//  exit('hello');
////  if ($block->getBaseId() === 'faq_contact_us') {
////    $build['#pre_render'][] = 'wristcheck_basic_block_poweredby_prerender';
////  }
//}
//
//function wristcheck_basic_block_poweredby_prerender(array $build) {
////  exit('hello');
//  $build['content']['#markup'] = Markup::create('Your text');
//  return $build;
//}
/**
 * Implements hook_theme().
 */
function wristcheck_basic_theme()
{
  return [
    'wristcheck_basic' => [
      'render element' => 'children',
    ],
    'wristcheck_homepage' => [
      'variables' => ['test_var' => NULL],
    ],
    'wristcheck_buy' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_category' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_user_info' => [
      'variables' => [
        'variables' => []
      ]
    ],

    'wristcheck_user_buy' => [
      'variables' => [
        'variables' => []
      ]
    ],

    'wristcheck_user_sell' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_user_portfolio' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_profile_payment_main' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_payment_success' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_payment_step' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_discover' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_magazine' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_single' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_user_useractivate' => [
      'variables' => [
        'variables' => []
      ]
    ],

    'wristcheck_faq_sellstep' => [],
    'wristcheck_faq_authsystem' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_faq_authsystemstep' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_eshop' => [],
    'wristcheck_faq' => [],
    'wristcheck_user_supplement_form' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_sell' => [],
    'wristcheck_banner_block' => [
      'variables' => []
    ],
    'wristcheck_faq_checkout_block' => [
      'variables' => [
           'variables' => []
      ]
    ],
    'wristcheck_faq_checkvalue_block' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_download_app_block' => [
      'variables' => []
    ],
    'wristcheck_paymentstep_block' => [
      'variables' => []
    ],
    'wristcheck_selling_process_block' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_search_product_block' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_free_advertising_block' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_sell_video_block' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_selling_process_single_image_block'=>[
      'variables' => [
        'variables' => []
      ]
    ]
  ];
}

function wristcheck_basic_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  $term_id = \Drupal::routeMatch()->getParameter('taxonomy_term');
  if ($term_id && $view->id() == 'product_list') {
    $term = \Drupal\taxonomy\Entity\Term::load($term_id);
    $type = $term->getVocabularyId();
    foreach ($query->where as $windex => &$condition_group) {
      foreach ($condition_group['conditions'] as $index => &$condition) {
        if ($type === 'brand' && $condition['field'] === 'commerce_product__field_cate.field_cate_target_id = :commerce_product__field_cate_field_cate_target_id') {
          unset($query->where[$windex]['conditions'][$index]);
        }
        if ($type === 'brand' && $condition['field'] === 'commerce_product__field_brand.field_brand_target_id = :commerce_product__field_brand_field_brand_target_id') {
          $query->where[$windex]['conditions'][$index]['value'] =
            [
              ':commerce_product__field_brand_field_brand_target_id' => $term_id
            ];
        }
        if ($type === 'product_tags' && $condition['field'] === 'commerce_product__field_brand.field_brand_target_id = :commerce_product__field_brand_field_brand_target_id') {
          unset($query->where[$windex]['conditions'][$index]);
        }

        if ($type === 'product_tags' && $condition['field'] === 'commerce_product__field_cate.field_cate_target_id = :commerce_product__field_cate_field_cate_target_id') {
          $query->where[$windex]['conditions'][$index]['value'] = [
            ':commerce_product__field_cate_field_cate_target_id' => $term_id
          ];
        }
      }
    }
  }
}
