<?php

/**
 * @file
 * Contains wristcheck_basic.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Markup;
/**
 * Implements hook_help().
 */
function wristcheck_basic_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the wristcheck_basic module.
    case 'help.page.wristcheck_basic':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('WristCheck Basic functions &amp; forms &amp; configurations &amp; pages.') . '</p>';
      return $output;

    default:
  }
}


//function wristcheck_basic_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
//  if ($block->getBaseId() === 'wristcheck_faq_checkout_block') {
//    $build['#pre_render'][] = 'wristcheck_basic_block_poweredby_prerender';
//  }
//}
//
//function wristcheck_basic_block_poweredby_prerender(array $build) {
//  $build['content']['#markup'] = Markup::create('Your text');
//  return $build;
//}
/**
 * Implements hook_theme().
 */
function wristcheck_basic_theme()
{
  return [
    'wristcheck_basic' => [
      'render element' => 'children',
    ],
    'wristcheck_homepage' => [
      'variables' => ['test_var' => NULL],
    ],
    'wristcheck_buy' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_category' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_user_info' => [
      'variables' => [
        'variables' => []
      ]
    ],

    'wristcheck_user_buy' => [
      'variables' => [
        'variables' => []
      ]
    ],

    'wristcheck_user_sell' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_user_portfolio' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_profile_payment_main' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_discover' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_magazine' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_faq_sellstep' => [],
    'wristcheck_faq_authsystemstep' => [],
    'wristcheck_eshop' => [],
    'wristcheck_faq' => [],
    'wristcheck_sell' => [],
    'wristcheck_banner_block' => [
      'variables' => []
    ],
    'wristcheck_faq_checkout_block' => [
      'variables' => [
           'variables' => []
      ]
    ],
    'wristcheck_faq_checkvalue_block' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_download_app_block' => [
      'variables' => []
    ],
    'wristcheck_selling_process_block' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_search_product_block' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_free_advertising_block' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_sell_video_block' => [
      'variables' => [
        'variables' => []
      ]
    ],
    'wristcheck_selling_process_single_image_block'=>[
      'variables' => [
        'variables' => []
      ]
    ]
  ];
}
