# Schema for the configuration files of the Radioactivity module.

field.storage_settings.radioactivity:
  type: mapping
  label: 'Radioactivity settings'
  mapping:
    profile:
      type: string
      label: 'Energy profile'
    granularity:
      type: integer
      label: 'Granularity'
    halflife:
      type: integer
      label: 'Half-life time'
    cutoff:
      type: float
      label: 'Cutoff'

field.field_settings.radioactivity:
  type: mapping
  label: 'Radioactivity settings'

field.value.radioactivity:
  type: mapping
  label: 'Default value'
  mapping:
    energy:
      type: float
      label: 'Energy'
    timestamp:
      type: integer
      label: 'Timestamp'

field.widget.settings.radioactivity_energy:
  type: mapping
  label: 'Radioactivity energy widget settings'
  mapping:
    energy:
      type: float
      label: 'Energy'
    timestamp:
      type: string
      label: 'Timestamp'

field.formatter.settings.radioactivity_emitter:
  type: mapping
  label: 'Radioactivity emitter format settings'
  mapping:
    energy:
      type: float
      label: 'Energy'
    display:
      type: string
      label: 'Energy'

field.formatter.settings.radioactivity_value:
  type: mapping
  label: 'Radioactivity value format settings'
  mapping:
    decimals:
      type: float
      label: 'Decimals'
